services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    tty: true
    stdin_open: true
    ports:
      - "8080:80"
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: pythonTest
    volumes:
      - ./docker/pg:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data:
